Repository labring/fastgpt-home, pull requests merged in 2024-09, with the labels that each got.

#45 add NEXT_PUBLIC_FILING_ADDRESS
  .github/workflows/fastgpt-home-image.yml
  projects/fastgpt/Dockerfile
  projects/fastgpt/components/footer/Footer.tsx
Labels: size/XS

#46 update Dockerfile
  projects/fastgpt/Dockerfile
Labels: size/XS

#47 Update workflow for building landingpage image
  .github/workflows/fastgpt-home-image.yml
Labels: size/S

#48 update
  .github/workflows/fastgpt-home-image.yml
  projects/fastgpt/Dockerfile
Labels: size/XS

#50 Add workflow to preview home page
  .github/workflows/preview.yml
Labels: size/M

#51 Update workflow to Preview home page
  .github/workflows/preview.yml
Labels: size/XS

#53 Update preview workflow
  .github/workflows/preview.yml
Labels: size/XS

#55 Update preview workflow
  .github/workflows/preview.yml
Labels: size/S

#57 Update preview workflow
  .github/workflows/preview.yml
Labels: size/XS

#59 Update preview workflow
  .github/workflows/preview.yml
Labels: size/XS

#61 Update preview workflow
  .github/workflows/preview.yml
Labels: size/XS

#63 Update preview workflow
  .github/workflows/preview.yml
Labels: size/M

#65 Add gh-rebot config
  .github/gh-bot.yml
Labels: size/M
