Repository labring/fastgpt-home, pull requests merged in 2024-05, with the labels that each got.

#27 Update opengraph image
  projects/fastgpt/public/og.png
  projects/fastgpt/public/opengraph-image.png
Labels: size/XS

#28 Update twitter image
  projects/fastgpt/public/twitter-image.png
Labels: size/XS

#29 add github stars
  .prettierrc.js
  projects/fastgpt/app/[[...lang]]/page.tsx
  projects/fastgpt/components/home/CTA.tsx
  projects/fastgpt/components/home/CTAButton.tsx
  projects/fastgpt/components/home/Hero.tsx
  projects/fastgpt/config/site.ts
  projects/fastgpt/middleware.ts
Labels: size/M

#30 Add baidu ziyuan
  projects/fastgpt/public/baidu_verify_codeva-mpHTn35uE0.html
Labels: size/XS

#32 add meta
  projects/fastgpt/app/layout.tsx
  projects/fastgpt/components/header/Header.tsx
Labels: size/XS

#33 fix github star
  package.json
  pnpm-lock.yaml
  projects/fastgpt/app/[[...lang]]/page.tsx
  projects/fastgpt/components/header/LangSwitcher.tsx
  projects/fastgpt/components/home/CTA.tsx
  projects/fastgpt/components/home/CTAButton.tsx
  projects/fastgpt/components/home/Hero.tsx
Labels: size/L

#34 fix github stars
  projects/fastgpt/app/[[...lang]]/page.tsx
  projects/fastgpt/components/home/CTA.tsx
  projects/fastgpt/components/home/CTAButton.tsx
  projects/fastgpt/components/home/Hero.tsx
Labels: size/M

#35 add google.html
  projects/fastgpt/public/google9e9d3599ff54f9dd.html
Labels: size/XS

#36 fix docs link
  projects/fastgpt/config/site.ts
  projects/fastgpt/locales/ar.json
  projects/fastgpt/locales/en.json
  projects/fastgpt/locales/es.json
  projects/fastgpt/locales/ja.json
  projects/fastgpt/locales/ru.json
  projects/fastgpt/locales/zh.json
Labels: size/M

#37 add Terms of Service
  projects/fastgpt/components/footer/Footer.tsx
  projects/fastgpt/components/footer/FooterLinks.tsx
  projects/fastgpt/components/footer/FooterProducts.tsx
  projects/fastgpt/components/footer/LangLinks.tsx
  projects/fastgpt/config/site.ts
  projects/fastgpt/locales/en.json
Labels: size/M

#38 Use localStorage to store lang
  projects/fastgpt/components/header/LangSwitcher.tsx
Labels: size/XS
