Repository labring/fastgpt-home, pull requests merged in 2024-07, with the labels that each got.

#40 update baidu key
  projects/fastgpt/app/BaiDuAnalytics.tsx
  projects/fastgpt/app/layout.tsx
Labels: size/M

#31 优化SEO
  projects/fastgpt/config/site.ts
Labels: size/XS

#41 Update workflow for building oci image
  .github/workflows/fastgpt-home-image.yml
Labels: size/XS

#42 fix BaiDuAnalytics
  projects/fastgpt/app/BaiDuAnalytics.tsx
Labels: size/S
