Repository labring/fastgpt-home, pull requests merged in 2025-07, with the labels that each got.

#82 add msclkid
  projects/fastgpt/components/home/CTAButton.tsx
Labels: size/XS

#83 home deploy
  .github/fastgpt-home-image.yml
  .github/gh-bot.yml
  .github/preview.yml
  .github/workflows/deploy.yml
  .github/xiaoyi-home-image.yml
  projects/fastgpt/Dockerfile
  projects/fastgpt/config/site.ts
  projects/fastgpt/locales/ar.json
  projects/fastgpt/locales/en.json
  projects/fastgpt/locales/es.json
  projects/fastgpt/locales/ja.json
  projects/fastgpt/locales/ru.json
  projects/fastgpt/locales/zh.json
  projects/fastgpt/next-sitemap.config.js
  projects/xiaoyi/src/pages/components/Footer.tsx
  projects/xiaoyi/src/pages/components/Navbar.tsx
Labels: size/L

#84 Remove rediret
  projects/fastgpt/app/layout.tsx
  projects/fastgpt/components/header/LangSwitcher.tsx
Labels: size/S

#86 action
  .github/workflows/fastgpt-home-image.yml
  .github/workflows/preview.yml
  projects/fastgpt/Dockerfile
  projects/fastgpt/components/home/Hero.tsx
Labels: size/M

#89 update crm
  projects/fastgpt/config/site.ts
  projects/fastgpt/locales/zh.json
Labels: size/XS
